#ifndef BINOUT_DEFINES_H
#define BINOUT_DEFINES_H

#define BINOUT_HEADER_BIG_ENDIAN 0
#define BINOUT_HEADER_LITTLE_ENDIAN 1
#define BINOUT_HEADER_FLOAT_IEEE 0

#define BINOUT_COMMAND_NULL 1
#define BINOUT_COMMAND_CD 2
#define BINOUT_COMMAND_DATA 3
#define BINOUT_COMMAND_VARIABLE 4
#define BINOUT_COMMAND_BEGINSYMBOLTABLE 5
#define BINOUT_COMMAND_ENDSYMBOLTABLE 6
#define BINOUT_COMMAND_SYMBOLTABLEOFFSET 7

#endif