name: build-on-push
run-name: ${{ github.actor }} is running this workflow
on: [push]

env:
  TEST_CASES: d3_buffer_seek,_get_nth_digit,_insert_sorted,d3_word_binary_search,Array,glob,string_builder,Array::New,binout_directory,path_move_up,path_join,path_is_abs,path_view,extra_string,card_parse_get_type,empty_card,profiling,sync,multi_file

jobs:
  linux-x86_64-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p linux -a x86_64 -k static -m release --build_test=y
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  linux-x86_64-static-profiling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p linux -a x86_64 -k static -m release --build_test=y --profiling=y
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  linux-x86_64-static-non-thread-safe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p linux -a x86_64 -k static -m release --build_test=y --thread_safe=n
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  linux-x86_64-static-profiling-non-thread-safe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p linux -a x86_64 -k static -m release --build_test=y --profiling=y --thread_safe=n
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  linux-x86_64-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p linux -a x86_64 -k static -m release --build_python=y
      - run: xmake -wvD


  windows-x64-static:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p windows -a x64 -k static -m release --build_test=y
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=%TEST_CASES%
  windows-x64-static-profiling:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p windows -a x64 -k static -m release --build_test=y --profiling=y
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=%TEST_CASES%
  windows-x64-static-non-thread-safe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p windows -a x64 -k static -m release --build_test=y --thread_safe=n
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=%TEST_CASES%
  windows-x64-static-profiling-non-thread-safe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p windows -a x64 -k static -m release --build_test=y --profiling=y --thread_safe=n
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=%TEST_CASES%
  windows-x64-python:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p windows -a x64 -k static -m release --build_python=y
      - run: xmake -wvD
