name: Build and Test
on: [push]

env:
  TEST_CASES: d3_buffer_seek,_get_nth_digit,_insert_sorted,d3_word_binary_search,Array,glob,string_builder,Array::New,binout_directory,path_move_up,path_join,path_is_abs,path_view,extra_string,card_parse_get_type,empty_card,profiling,sync,multi_file
  PYTHON_TEST_CODE: |
    import dynareadout as dro

jobs:
  build-and-test:
    runs-on: ${{ matrix.plat == 'linux' && 'ubuntu' || matrix.plat }}-latest
    strategy:
      fail-fast: false
      matrix:
        plat: [linux, windows]
        arch: [x86_64]
        kind: [static]
        thread_safe: [y, n]
        profiling: [y, n]
        python: [y, n]
    env:
      arch: ${{ matrix.plat == 'windows' && 'x64' || matrix.arch }}
    name: ${{ matrix.plat }}-${{ matrix.plat == 'windows' && 'x64' || matrix.arch }}-${{ matrix.kind }}${{ matrix.thread_safe == 'y' && '-thread-safe' || '-non-thread-safe' }}${{ matrix.profiling == 'y' && '-profiling' || '-not-profiling' }}${{ matrix.python == 'y' && '-python' || '-c' }}

    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - uses: actions/setup-python@v5
        if: matrix.python == 'y'
        with:
          python-version: '3.11'
      - run: xmake f -yvD -p ${{ matrix.plat }} -a ${{ env.arch }} -k ${{ matrix.kind }} -m release --build_test=y --thread_safe=${{ matrix.thread_safe }} --profiling=${{ matrix.profiling }} --build_python=${{ matrix.python }}
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=${{ env.TEST_CASES }}
        if: matrix.python == 'n'
      - run: ls -la --color=always build/${{ matrix.plat }}/${{ env.arch }}/release
        if: matrix.python == 'y' && matrix.plat != 'windows'
      - run: dir build/${{ matrix.plat }}/${{ env.arch }}/release
        if: matrix.python == 'y' && matrix.plat == 'windows'
      - run: echo ${{ env.PYTHON_TEST_CODE }}
        if: matrix.python == 'y'
      - run: cd build/${{ matrix.plat }}/${{ env.arch }}/release && python ${{ github.workspace }}/src/python/test.py
        if: matrix.python == 'y'
