name: build-on-push
run-name: ${{ github.actor }} is running this workflow
on: [push]

env:
  TEST_CASES: d3_buffer_seek,_get_nth_digit,_insert_sorted,d3_word_binary_search,Array,glob,string_builder,Array::New,binout_directory,path_move_up,path_join,path_is_abs,path_view,extra_string,card_parse_get_type,empty_card,profiling,sync,multi_file
  PYTHON_TEST_CODE: |
    import dynareadout as dro

jobs:
  linux-x86_64-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p linux -a x86_64 -k static -m release --build_test=y
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  linux-x86_64-static-profiling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p linux -a x86_64 -k static -m release --build_test=y --profiling=y
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  linux-x86_64-static-non-thread-safe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p linux -a x86_64 -k static -m release --build_test=y --thread_safe=n
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  linux-x86_64-static-profiling-non-thread-safe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p linux -a x86_64 -k static -m release --build_test=y --profiling=y --thread_safe=n
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  linux-x86_64-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: xmake f -yvD -p linux -a x86_64 -k static -m release --build_python=y
      - run: xmake -wvD
      - run: ls -la --color=always build/linux/x86_64/release
      - run: echo $PYTHON_TEST_CODE
      - run: cd build/linux/x86_64/release && echo $PYTHON_TEST_CODE | python


  windows-x64-static:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p windows -a x64 -k static -m release --build_test=y
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$env:TEST_CASES
  windows-x64-static-profiling:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p windows -a x64 -k static -m release --build_test=y --profiling=y
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$env:TEST_CASES
  windows-x64-static-non-thread-safe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p windows -a x64 -k static -m release --build_test=y --thread_safe=n
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$env:TEST_CASES
  windows-x64-static-profiling-non-thread-safe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p windows -a x64 -k static -m release --build_test=y --profiling=y --thread_safe=n
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$env:TEST_CASES
  windows-x64-python:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: xmake f -yvD -p windows -a x64 -k static -m release --build_python=y
      - run: xmake -wvD
      - run: echo $env:PYTHON_TEST_CODE
      - run: cd build/windows/x64/release && dir && echo $env:PYTHON_TEST_CODE | python


  macos-x86_64-static:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p macos -a x86_64 -k static -m release --build_test=y
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  macos-x86_64-static-profiling:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p macos -a x86_64 -k static -m release --build_test=y --profiling=y
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  macos-x86_64-static-non-thread-safe:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p macos -a x86_64 -k static -m release --build_test=y --thread_safe=n
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
  macos-x86_64-static-profiling-non-thread-safe:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -yvD -p macos -a x86_64 -k static -m release --build_test=y --profiling=y --thread_safe=n
      - run: xmake -wvD
      - run: xmake run -w . dynareadout_test --test-case=$TEST_CASES
