name: build-on-push
run-name: ${{ github.actor }} is running this workflow
on: [push]
jobs:
  linux-x86_64-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -y -p linux -a x86_64 -m release --build_test=y
      - run: xmake -wvD
  linux-x86_64-static-profiling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -y -p linux -a x86_64 -m release --build_test=y --profiling=y
      - run: xmake -wvD
  linux-x86_64-static-non-thread-safe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -y -p linux -a x86_64 -m release --build_test=y --thread_safe=n
      - run: xmake -wvD
  linux-x86_64-static-profiling-non-thread-safe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 2.8.6
      - run: xmake f -y -p linux -a x86_64 -m release --build_test=y --profiling=y --thread_safe=n
      - run: xmake -wvD
